export const INDICATOR1_TYPES = {
  DPT_DOUGHNUT_CHART: 'DPT_DOUGHNUT_CHART',
  MEDIUM_REFERENCE_LINEAR_SCALE: 'MEDIUM_REFERENCE_LINEAR_SCALE',
  BIMEDIUM_REFERENCE_LINEAR_SCALE: 'BIMEDIUM_REFERENCE_LINEAR_SCALE',
  MIXED_VERTICAL_BAR_CHART_MEDIUM_REFERENCE_LINEAR_SCALE: 'MIXED_VERTICAL_BAR_CHART_MEDIUM_REFERENCE_LINEAR_SCALE',
  NOMINAL_SCALE: 'NOMINAL_SCALE',
  BINOMINAL_SCALE: 'BINOMINAL_SCALE',
};
